services:
  pentest-sandbox:
    build:
      context: .
      dockerfile: Dockerfile.pentest-sandbox
    image: pentest-sandbox:latest
    container_name: pentest-sandbox
    privileged: true
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    mem_limit: 2g
    cpus: 2
    working_dir: /workspace
    networks:
      pentest_lab:
        ipv4_address: 172.22.0.10

  metasploitable2:
    image: tleemcjr/metasploitable2:latest
    container_name: metasploitable2
    command: ["sh", "-c", "/bin/services.sh || true; tail -f /dev/null"] # Para mantenerlo despierto
    networks:
      pentest_lab:
        ipv4_address: 172.22.0.20

networks:
  pentest_lab:
    name: pentest_lab
    internal: true
    ipam:
      config:
        - subnet: 172.22.0.0/24
